name: arkod_wp_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  postgres: ^2.4.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.4
