name: arkod_wp_core
description: ARKOD WordPress core library providing models, utilities and features shared by ARKOD WordPress toolkit modules.
version: 0.0.3
homepage: https://arkod.fr
repository: https://github.com/arkod-team/arkod_wp_core

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  postgres: ^2.4.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.2
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
